### ISSUE TITLE
Cannot kick off scan

### ISSUE THREAD

**Issue by jdamata** [webbreaker/webbreaker#1]
### Subject of the issue
Can't kickoff scan. 

### Your environment
python 2.7.15
webbreaker Version 2.2.2

### Relevant WebBreaker commands
```
$ python __main__.py webinspect scan --settings Default --username $WEBINSPECT_USER --password $WEBINSPECT_PASSWORD --scan_name test

 _       __     __    ____                  __
| |     / /__  / /_  / __ )________  ____ _/ /_____  _____
| | /| / / _ \/ __ \/ __  / ___/ _ \/ __ `/ //_/ _ \/ ___/
| |/ |/ /  __/ /_/ / /_/ / /  /  __/ /_/ / ,< /  __/ /
|__/|__/\___/_.___/_____/_/   \___/\__,_/_/|_|\___/_/


Version 2.2.2
Logging to files: /Users/damatj/.webbreaker/log/webbreaker-04-02-2019.log
A large server will be selected to handle this request.
Querying WebInspect servers for availability.
ls -lrth /Users/damatj/.webbreaker/logThe search has timed out after 30 seconds.
Traceback (most recent call last):
  File "__main__.py", line 493, in <module>
    cli()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "__main__.py", line 157, in webinspect_scan
    WebInspectScan(kwargs.copy())
  File "build/bdist.macosx-10.13-x86_64/egg/webbreaker/webinspect/scan.py", line 72, in __init__
  File "build/bdist.macosx-10.13-x86_64/egg/webbreaker/webinspect/scan.py", line 352, in __init__
  File "build/bdist.macosx-10.13-x86_64/egg/webbreaker/webinspect/scan.py", line 618, in get_endpoint
  File "build/bdist.macosx-10.13-x86_64/egg/webbreaker/webinspect/jit_scheduler.py", line 65, in get_endpoint
  File "build/bdist.macosx-10.13-x86_64/egg/webbreaker/webinspect/jit_scheduler.py", line 100, in _get_available_endpoint
webbreaker.webinspect.jit_scheduler.NoServersAvailableError: The JIT Scheduler found no available servers for this request.
```

Listed running scans to be sure my config was working
```
$ python __main__.py webinspect list

 _       __     __    ____                  __
| |     / /__  / /_  / __ )________  ____ _/ /_____  _____
| | /| / / _ \/ __ \/ __  / ___/ _ \/ __ `/ //_/ _ \/ ___/
| |/ |/ /  __/ /_/ / /_/ / /  /  __/ /_/ / ,< /  __/ /
|__/|__/\___/_.___/_____/_/   \___/\__,_/_/|_|\___/_/


Version 2.2.2
Logging to files: /Users/damatj/.webbreaker/log/webbreaker-04-02-2019.log
Using webinspect server: -->http://redacted:8083/webinspect/<-- for query
No scans found on http://redacted:8083/webinspect/
```

**Comment by xolian** [comment]
Sorry for the delay, are you able to launch a scan from your Webinspect API from a POST from scanner/scan ?  Additionally, it is not necessary to call __main__.py directly just install it or use the pyinstaller setup arg from `python setup.py pyinstaller`
